Update print statements to make it Py3 compatible
rix0rrr/cover2cover pull request #6
Opened 2019-04-29 08:38 UTC by captainmalloc

Just a small update to make it run with Python 3

2019-10-21 14:12 UTC, EpicEric requested changes

2019-10-21 14:12 UTC, EpicEric commented on cover2cover.py
> +    print(ET.tostring(into))
They've changed the behavior of `ET.tostring` in Python3. This should be:

```python3
print(ET.tostring(into, encoding='unicode'))
```

2019-10-25 13:16 UTC, EpicEric approved these changes

2020-01-24 23:00 UTC, MikeDombo commented
I'd love to use this script, can this get merged?

2021-12-07 14:35 UTC, kayman-mk commented
@rix0rrr Any chance to get this PR merged?

2023-07-23 14:11 UTC, rix0rrr commented
Fixed by merging another PR

2023-07-23 14:11 UTC, closed without merging